#!/usr/bin/python
# Author: mayankmethad
import itertools, sys	
charlist=''
cnt=0
if sys.argv[1] == '-m':
	cnt=int(sys.argv[2])
if sys.argv[3] == '-c':
	charlist=sys.argv[4]
i=1
while i <= cnt:
	res = itertools.product(charlist, repeat=i)
	for j in res:
		print ''.join(j)
	i=i+1
