#!/usr/bin/python
# Author: mayankmethad
import itertools, sys, time
sTime = time.time()	
charlist=''
cnt=0
outf="GenList"
i=1
if sys.argv[1] == '-m':
	i=int(sys.argv[2])
if sys.argv[3] == '-n':
	cnt=int(sys.argv[4])
if sys.argv[5] == '-c':
	charlist=sys.argv[6]
elif sys.argv[5] == '-i':
	fi=open(sys.argv[6],"r")
	charlist=fi.read()
	fi.close()
if(len(sys.argv)>=8):
	if sys.argv[7] == '-o':
		outf=sys.argv[8]
fo=open(outf,"w")
while i <= cnt:
	res = itertools.product(charlist, repeat=i)
	for j in res:
		fo.write(str(''.join(j))+"\n")
		if (time.time()-sTime)%10 == 0:
			print "[%15.2f s] Generated: " % (time.time()-sTime) +''.join(j)
	i=i+1
fo.close()
print 'Execution time: %.2f s' % (time.time()-sTime)	
